### ISSUE TITLE
Add Fishing to wiki

### ISSUE THREAD

**Issue by hellodhruvin** [XeDotCom/villager-bot-wiki#22]
We already have mobs, mining to wiki, adding fishing would also be great. again idk what's going on with the bot so cannot help there.

**Comment by hellodhruvin** [comment]
Will make my pr rely on this atm.

**Comment by XeDotCom** [comment]
if you check the shop page, you'll see that i hage made a section for it, but i don't have anything there cause fishing is still in bets

**Comment by XeDotCom** [comment]
beta

**Comment by XeDotCom** [comment]
fishing is done i guess lmao
